# Generated by Django 2.0.9 on 2018-11-07 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_filename', models.CharField(default='con050217.csv', max_length=250)),
                ('link_counts', models.IntegerField()),
                ('start_time', models.CharField(default='2018-05-02T17:00', max_length=100)),
                ('end_time', models.CharField(default='2018-05-02T17:01', max_length=100)),
                ('size', models.IntegerField(default=2)),
                ('community_counts', models.IntegerField(default=0)),
                ('ip_counts', models.IntegerField(default=0)),
                ('result_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
