# Generated by Django 2.0.9 on 2018-11-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='size',
            new_name='smallest_size',
        ),
        migrations.AlterField(
            model_name='result',
            name='link_counts',
            field=models.IntegerField(default=0),
        ),
    ]
