# Generated by Django 2.0.9 on 2018-11-07 16:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_result_result_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('community_tag', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('leader_ip', models.CharField(default='', max_length=20)),
                ('ip_counts', models.IntegerField(default=0)),
                ('link_counts', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='result',
            name='id',
        ),
        migrations.AlterField(
            model_name='result',
            name='result_filename',
            field=models.CharField(default='con050217.csv_2018-05-02T1700_2018-05-02T1701_2.csv', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 7, 16, 9, 21, 591667)),
        ),
        migrations.AddField(
            model_name='community',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Result'),
        ),
    ]
